### ISSUE TITLE
Mocking tornadis during unittests

### ISSUE THREAD

**Issue by kardaj** [thefab/tornadis#29]
I'm currently working with tornadis, and I'm wondering if there's a way to mock this project during tests the same way [mockredis](https://github.com/locationlabs/mockredis) can mock [redis](https://github.com/andymccurdy/redis-py)

**Comment by thefab** [comment]
It's a complex thing because you have to find (write ?) a mock library which interacts in a async way with the tornado ioloop (see tornadis unit tests which use specific AsyncTestCase class provided by the tornado framework).

So a good tornadis mocking library would probably be tornado specific.

And I don't know a such project :-(

**Comment by hunt3r** [comment]
Yeah, use the AsyncTestCase for mocking async client tests.  we use the `mock`, you'll want to setup your application client to inject the tornadis client into it through the constructor, then in your clients TestCase you'll pass a new `self.mock_tornadis_client = Mock()` into the constructor instead of the Tornadis client.  Since everything in Python is pass by reference, you can then use the `self.mock_torandis.side_effect` to mock any responses you expect from the tornadis client in your code.
